spring:
  messages:
    basename: i18n/validate  #   \u9A8C\u8BC1\u6587\u4EF6\u7684\u8DEF\u5F84
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.223.121:3306/shangou_db_test?serverTimezone=Asia/Shanghai  # \u6570\u636E\u5E93\u7684\u65F6\u533A\u5730\u5740
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss  #\u7EDF\u4E00\u8FDB\u884C\u65E5\u671F\u683C\u5F0F\u7684\u6570\u636E\u8FD4\u56DE
      time-zone: Asia/Shanghai   # \u9ED8\u8BA4\u65F6\u533A
    servlet:
      multipart:
        max-file-size: 5MB  #\u5355\u4E2A\u6587\u4EF6\u6700\u59275MB
        max-request-size: 100MB #\u4E00\u6B21\u8BF7\u6C42\u6700\u5927\u4E00\u767E\u5146
  mybatis:
    configuration:
      map-underscore-to-camel-case: true  #  \u4E0B\u5212\u7EBF\u8F6C\u6362\u7A0B\u9A7C\u5CF0
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #  \u65E5\u5FD7\u4E5F\u53EF\u4EE5\u8FD9\u4E48\u914D\u7F6E
    mapper-locations: classpath*:mybatis/mapper/**/*.xml  # mapper.xml\u6587\u4EF6\u7684\u8DEF\u5F84\u914D\u7F6E
  server:
    servlet:
      context-path: /  # \u8FD9\u4E2A\u662F\u914D\u7F6E\u9879\u76EE\u4E0A\u4E0B\u6587\u8DEF\u5F84
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/shangou_db?serverTimezone=Asia/Shanghai  # \u6570\u636E\u5E93\u7684\u65F6\u533A\u5730\u5740
server:
  port: 80
---
logging:
  level:
    com.onedao: trace  #   \u5F00\u53D1\u73AF\u5883\u7684\u65F6\u5019\uFF0Cdao\u5305\u8F93\u51FA\u7684\u65E5\u5FD7\u7EA7\u522B\u662Ftrace
spring:
  profiles: dev
server:
  port: 80